[package]
name = "bzlq"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
anyhow = "1.0.71"
protobuf = "3.2.0"
regex = "1.8.1"

[build-dependencies]
protobuf-codegen = "3.2.0"
protoc-bin-vendored = "3.0.0"
